import Head from 'next/head'
import styled from 'styled-components'
import { ExampleComponent } from '../components/exampleComponent'
import styles from '../styles/Home.module.css'

const Row = styled.div`
    display: flex;
    margin: 10px 0;
    flex-direction: row;
    justify-content: space-between;
    gap: 20px;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ExampleComponent />
        <Row>
          <ExampleComponent />
          <ExampleComponent />
          <ExampleComponent />
        </Row>
      </main>
    </div>
  )
}
